/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.evors.rs.ui.GASetup;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.evors.rs.sim.robot.ctrnn.CTRNNLayout;
import org.evors.rs.sim.robot.ctrnn.io.JSONCTRNNLayout;
import org.evors.rs.ui.utils.UIUtils;

/**
 *
 * @author miles
 */
public class ControllerLoad extends javax.swing.JPanel {

    /**
     * Creates new form ControllerLoad
     */
    public ControllerLoad() {
        initComponents();
    }

    
    CTRNNLayout layout;

    public CTRNNLayout getCTRNNLayout() {
        return layout;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fcController = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        lblDesc2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblAuthor2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        fcController.setApproveButtonText("Open");
        fcController.setControlButtonsAreShown(false);
        fcController.setCurrentDirectory(UIUtils.getUserDir("/CTRNN Layouts/"));
        fcController.setDialogTitle("");
        fcController.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcControllerActionPerformed(evt);
            }
        });
        fcController.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fcControllerPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.55;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(fcController, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblDesc2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(10, 7, 10, 7);
        jPanel2.add(lblDesc2, gridBagConstraints);

        jLabel10.setText("Description:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 7, 10, 7);
        jPanel2.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Author:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 7, 10, 7);
        jPanel2.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(10, 7, 10, 7);
        jPanel2.add(lblAuthor2, gridBagConstraints);

        jLabel12.setText("Title:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 7, 10, 7);
        jPanel2.add(jLabel12, gridBagConstraints);

        lblTitle2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(10, 7, 10, 7);
        jPanel2.add(lblTitle2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.45;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void fcControllerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcControllerActionPerformed
        
    }//GEN-LAST:event_fcControllerActionPerformed

    private void fcControllerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fcControllerPropertyChange
        try {
            JSONCTRNNLayout jlayout = JSONCTRNNLayout.fromFile(fcController.getSelectedFile());
            lblAuthor2.setText(jlayout.getMetadata().getAuthor());
            lblTitle2.setText(jlayout.getMetadata().getTitle());
            lblDesc2.setText(jlayout.getMetadata().getDescription());
            layout=jlayout.toCTRNNLayout();
        } catch (Exception ex) {
            lblAuthor2.setText("<File not valid JSON CTRNN Layout file>");
        }
    }//GEN-LAST:event_fcControllerPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fcController;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAuthor2;
    private javax.swing.JLabel lblDesc2;
    private javax.swing.JLabel lblTitle2;
    // End of variables declaration//GEN-END:variables
}
