/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unisim.ui.frames;

import org.unisim.exp.Experiment;
import org.unisim.genesis.RobotGenotype;

/**
 *
 * @author miles
 */
public class TrialViewerFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form TrialViewerFrame
     */
    public TrialViewerFrame() {
        initComponents();
    }
    
    public void loadSimulation(Experiment exp,RobotGenotype geno) {
        simulationViewer1.loadSimulation(exp, geno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simulationViewer1 = new org.unisim.ui.sandpit.SimulationViewer();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Trial viewer");
        setDoubleBuffered(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simulationViewer1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simulationViewer1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.unisim.ui.sandpit.SimulationViewer simulationViewer1;
    // End of variables declaration//GEN-END:variables
}
